import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navigation
    appName: 'AgriSmart',
    tagline: 'AI Powered Farmer Super Platform',
    dashboard: 'Dashboard',
    cropRecommendation: 'Crop Recommendation',
    weather: 'Weather Monitoring',
    disease: 'Disease Detection',
    irrigation: 'Smart Irrigation',
    expenses: 'Expense Tracker',
    marketplace: 'Marketplace',
    schemes: 'Government Schemes',
    advisory: 'Crop Advisory',
    home: 'Home',
    settings: 'Settings',
    logout: 'Logout',
    language: 'Language',
    darkMode: 'Dark Mode',
    
    // Dashboard
    welcomeMessage: 'Welcome to AgriSmart',
    let: 'Let',
    grow: 'Grow Smarter',
    earn: 'Earn More',
    welcome: 'Welcome',
    farmSize: 'Farm Size',
    totalExpenses: 'Total Expenses',
    totalRevenue: 'Total Revenue',
    activeCrops: 'Active Crops',
    activeAlerts: 'Active Alerts',
    quickActions: 'Quick Actions',
    getCropRecommendation: 'Get Crop Recommendation',
    checkWeather: 'Check Weather',
    detectDisease: 'Detect Disease',
    trackExpenses: 'Track Expenses',
    viewSchemes: 'View Schemes',
    
    // Weather Monitoring
    weatherMonitoringSystem: 'Weather Monitoring System',
    realtimeWeatherData: 'Real-time weather data and forecasts for your farming location',
    enterLocation: 'Enter location (e.g., Punjab, Haryana)',
    getWeather: 'Get Weather',
    fetching: 'Fetching...',
    currentWeather: 'Current Weather',
    humidity: 'Humidity',
    precipitation: 'Precipitation',
    windSpeed: 'Wind Speed',
    forecast: 'Forecast',
    failedToFetchWeather: 'Failed to fetch weather data',
    pleaseEnterLocation: 'Please enter a location',
    
    // Disease Detection
    diseaseDetectionSystem: 'Disease Detection System',
    uploadCropImage: 'Upload your crop image here',
    clickToUpload: 'Click to browse or drag & drop',
    analyzeImage: 'Analyze Image',
    selectImage: 'Select Image',
    diseaseDetected: 'Disease Detected',
    noDisease: 'No Disease Detected',
    confidence: 'Confidence',
    severity: 'Severity',
    treatment: 'Treatment',
    pleaseSelectImage: 'Please select an image first',
    failedToAnalyzeImage: 'Failed to analyze image',
    
    // Crop Recommendation
    cropRecommendationForm: 'Crop Recommendation',
    soilType: 'Soil Type',
    location: 'Location',
    season: 'Season',
    temperature: 'Temperature (°C)',
    rainfall: 'Rainfall (mm)',
    clay: 'Clay',
    loam: 'Loam',
    sandy: 'Sandy',
    peat: 'Peat',
    kharif: 'Kharif (April-October)',
    rabi: 'Rabi (October-March)',
    summer: 'Summer (March-June)',
    getRecommendation: 'Get Recommendation',
    recommendedCrops: 'Recommended Crops',
    crop: 'Crop',
    suitability: 'Suitability',
    benefits: 'Benefits',
    
    // Smart Irrigation
    smartIrrigationSystem: 'Smart Irrigation System',
    cropType: 'Crop Type',
    rice: 'Rice',
    wheat: 'Wheat',
    corn: 'Corn',
    cotton: 'Cotton',
    sugarcane: 'Sugarcane',
    potato: 'Potato',
    getAdvice: 'Get Advice',
    irrigationSchedule: 'Irrigation Schedule',
    frequency: 'Frequency',
    waterQuantity: 'Water Quantity',
    duration: 'Duration',
    
    // Marketplace
    farmerMarketplace: 'Farmer Marketplace',
    buyAndSell: 'Buy and sell agricultural products directly - no middlemen',
    search: 'Search products...',
    searchProducts: 'Search Products',
    cart: 'Cart',
    addToCart: 'Add to Cart',
    removeFromCart: 'Remove from Cart',
    quantity: 'Quantity',
    price: 'Price',
    seller: 'Seller',
    rating: 'Rating',
    totalPrice: 'Total Price',
    checkout: 'Checkout',
    noItemsInCart: 'No items in cart',
    
    // Government Schemes
    governmentSchemes: 'Government Schemes',
    exploreAndApply: 'Explore and apply for government support schemes for farmers',
    availableSchemes: 'Available Schemes',
    schemeType: 'Scheme Type',
    eligibility: 'Eligibility',
    benefits: 'Benefits',
    applyNow: 'Apply Now',
    learnMore: 'Learn More',
    incomeSupport: 'Income Support',
    insurance: 'Insurance',
    advisoryScheme: 'Advisory',
    credit: 'Credit',
    
    // Crop Advisory
    cropAdvisorySystem: 'Crop Advisory System',
    getPersonalizedAdvice: 'Get personalized crop advisory based on your farm conditions',
    advisoryTips: 'Advisory Tips',
    soilManagement: 'Soil Management',
    pestManagement: 'Pest Management',
    weatherAdvice: 'Weather Advice',
    harvestingTips: 'Harvesting Tips',
    
    // Expense Tracker
    expenseTracker: 'Expense Tracker',
    manageYourFarmExpenses: 'Manage your farm expenses efficiently',
    addExpense: 'Add Expense',
    category: 'Category',
    seeds: 'Seeds',
    fertilizer: 'Fertilizer',
    labor: 'Labor',
    equipment: 'Equipment',
    pesticide: 'Pesticide',
    waterIrrigation: 'Water/Irrigation',
    transportation: 'Transportation',
    other: 'Other',
    date: 'Date',
    description: 'Description',
    amount: 'Amount',
    addNew: 'Add New',
    totalExpensesAmount: 'Total Expenses',
    expenseAnalysis: 'Expense Analysis',
    monthlyBreakdown: 'Monthly Breakdown',
    categoryBreakdown: 'Category Breakdown',
    
    // Common
    submit: 'Submit',
    cancel: 'Cancel',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    fillAllFields: 'Please fill all required fields',
  },
  hi: {
    // Navigation
    appName: 'कृषि स्मार्ट',
    tagline: 'AI द्वारा संचालित किसान सुपर प्लेटफॉर्म',
    dashboard: 'डैशबोर्ड',
    cropRecommendation: 'फसल की सिफारिश',
    weather: 'मौसम निगरानी',
    disease: 'रोग संचय',
    irrigation: 'स्मार्ट सिंचाई',
    expenses: 'खर्च ट्रैकर',
    marketplace: 'बाजारपल',
    schemes: 'सरकारी योजनाएं',
    advisory: 'फसल सलाह',
    home: 'घर',
    settings: 'सेटिंग्स',
    logout: 'लॉगआउट',
    language: 'भाषा',
    darkMode: 'डार्क मोड',
    
    // Dashboard
    welcomeMessage: 'कृषि स्मार्ट में आपका स्वागत है',
    let: 'आइए',
    grow: 'स्मार्ट तरीके से बढ़ें',
    earn: 'अधिक कमाएं',
    welcome: 'स्वागत है',
    farmSize: 'फार्म का आकार',
    totalExpenses: 'कुल खर्च',
    totalRevenue: 'कुल राजस्व',
    activeCrops: 'सक्रिय फसलें',
    activeAlerts: 'सक्रिय सतर्कताएं',
    quickActions: 'त्वरित कार्य',
    getCropRecommendation: 'फसल की सिफारिश प्राप्त करें',
    checkWeather: 'मौसम की जांच करें',
    detectDisease: 'रोग का पता लगाएं',
    trackExpenses: 'खर्च को ट्रैक करें',
    viewSchemes: 'योजनाएं देखें',
    
    // Weather Monitoring
    weatherMonitoringSystem: 'मौसम निगरानी प्रणाली',
    realtimeWeatherData: 'आपके कृषि स्थान के लिए वास्तविक समय मौसम डेटा और पूर्वानुमान',
    enterLocation: 'स्थान दर्ज करें (जैसे, पंजाब, हरियाणा)',
    getWeather: 'मौसम प्राप्त करें',
    fetching: 'प्राप्त कर रहे हैं...',
    currentWeather: 'वर्तमान मौसम',
    humidity: 'आर्द्रता',
    precipitation: 'वर्षा',
    windSpeed: 'हवा की गति',
    forecast: 'पूर्वानुमान',
    failedToFetchWeather: 'मौसम डेटा प्राप्त करने में विफल',
    pleaseEnterLocation: 'कृपया एक स्थान दर्ज करें',
    
    // Disease Detection
    diseaseDetectionSystem: 'रोग संचय प्रणाली',
    uploadCropImage: 'अपनी फसल की छवि यहां अपलोड करें',
    clickToUpload: 'ब्राउज़ करने के लिए क्लिक करें या ड्रैग और ड्रॉप करें',
    analyzeImage: 'छवि का विश्लेषण करें',
    selectImage: 'छवि चुनें',
    diseaseDetected: 'रोग पाया गया',
    noDisease: 'कोई रोग नहीं पाया गया',
    confidence: 'आत्मविश्वास',
    severity: 'गंभीरता',
    treatment: 'उपचार',
    pleaseSelectImage: 'कृपया पहले एक छवि चुनें',
    failedToAnalyzeImage: 'छवि का विश्लेषण करने में विफल',
    
    // Crop Recommendation
    cropRecommendationForm: 'फसल की सिफारिश',
    soilType: 'मृदा प्रकार',
    location: 'स्थान',
    season: 'मौसम',
    temperature: 'तापमान (°C)',
    rainfall: 'वर्षा (मिमी)',
    clay: 'चिकनी मिट्टी',
    loam: 'दोमट',
    sandy: 'बलुई',
    peat: 'पीट',
    kharif: 'खरीफ (अप्रैल-अक्टूबर)',
    rabi: 'रबी (अक्टूबर-मार्च)',
    summer: 'गर्मी (मार्च-जून)',
    getRecommendation: 'सिफारिश प्राप्त करें',
    recommendedCrops: 'अनुशंसित फसलें',
    crop: 'फसल',
    suitability: 'उपयुक्तता',
    benefits: 'लाभ',
    
    // Smart Irrigation
    smartIrrigationSystem: 'स्मार्ट सिंचाई प्रणाली',
    cropType: 'फसल का प्रकार',
    rice: 'चावल',
    wheat: 'गेहूं',
    corn: 'मक्का',
    cotton: 'कपास',
    sugarcane: 'गन्ना',
    potato: 'आलू',
    getAdvice: 'सलाह प्राप्त करें',
    irrigationSchedule: 'सिंचाई कार्यक्रम',
    frequency: 'आवृत्ति',
    waterQuantity: 'जल की मात्रा',
    duration: 'अवधि',
    
    // Marketplace
    farmerMarketplace: 'किसान बाजारपल',
    buyAndSell: 'कृषि उत्पादों को सीधे खरीदें और बेचें - बिना बिचौलियों के',
    search: 'उत्पादों को खोजें...',
    searchProducts: 'उत्पाद खोजें',
    cart: 'कार्ट',
    addToCart: 'कार्ट में जोड़ें',
    removeFromCart: 'कार्ट से हटाएं',
    quantity: 'मात्रा',
    price: 'कीमत',
    seller: 'विक्रेता',
    rating: 'रेटिंग',
    totalPrice: 'कुल कीमत',
    checkout: 'चेकआउट',
    noItemsInCart: 'कार्ट में कोई आइटम नहीं',
    
    // Government Schemes
    governmentSchemes: 'सरकारी योजनाएं',
    exploreAndApply: 'किसानों के लिए सरकारी समर्थन योजनाओं का अन्वेषण करें और आवेदन करें',
    availableSchemes: 'उपलब्ध योजनाएं',
    schemeType: 'योजना का प्रकार',
    eligibility: 'पात्रता',
    benefits: 'लाभ',
    applyNow: 'अभी आवेदन करें',
    learnMore: 'और जानें',
    incomeSupport: 'आय समर्थन',
    insurance: 'बीमा',
    advisoryScheme: 'सलाह',
    credit: 'ऋण',
    
    // Crop Advisory
    cropAdvisorySystem: 'फसल सलाह प्रणाली',
    getPersonalizedAdvice: 'अपनी खेत की स्थितियों के आधार पर व्यक्तिगत फसल सलाह प्राप्त करें',
    advisoryTips: 'सलाह के सुझाव',
    soilManagement: 'मृदा प्रबंधन',
    pestManagement: 'कीट प्रबंधन',
    weatherAdvice: 'मौसम की सलाह',
    harvestingTips: 'कटाई के सुझाव',
    
    // Expense Tracker
    expenseTracker: 'खर्च ट्रैकर',
    manageYourFarmExpenses: 'अपने खेत के खर्चों को कुशलतापूर्वक प्रबंधित करें',
    addExpense: 'खर्च जोड़ें',
    category: 'श्रेणी',
    seeds: 'बीज',
    fertilizer: 'खाद',
    labor: 'श्रम',
    equipment: 'उपकरण',
    pesticide: 'कीटनाशक',
    waterIrrigation: 'जल/सिंचाई',
    transportation: 'परिवहन',
    other: 'अन्य',
    date: 'तारीख',
    description: 'विवरण',
    amount: 'राशि',
    addNew: 'नया जोड़ें',
    totalExpensesAmount: 'कुल खर्च',
    expenseAnalysis: 'खर्च विश्लेषण',
    monthlyBreakdown: 'मासिक विवरण',
    categoryBreakdown: 'श्रेणी विवरण',
    
    // Common
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफल',
    fillAllFields: 'कृपया सभी आवश्यक क्षेत्र भरें',
  },
  pa: {
    // Navigation
    appName: 'ਕ੃ਸੀ ਸਮਾਰਟ',
    tagline: 'AI ਦੁਆਰਾ ਸ਼ਕਤੀ ਪ੍ਰਾਪਤ ਕਿਸਾਨ ਸੁਪਰ ਪਲੇਟਫਾਰਮ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    cropRecommendation: 'ਫਸਲ ਸਿਫਾਰਸ਼',
    weather: 'ਮੌਸਮ ਦੀ ਨਿਗਰਾਨੀ',
    disease: 'ਰੋਗ ਪਤਾ ਲਗਾਉਣਾ',
    irrigation: 'ਸਮਾਰਟ ਸਿੰਚਾਈ',
    expenses: 'ਖਰਚ ਟਰੈਕਰ',
    marketplace: 'ਮਾਰਕੀਟਪਲੇਸ',
    schemes: 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ',
    advisory: 'ਫਸਲ ਸਲਾਹ',
    home: 'ਘਰ',
    settings: 'ਸੈਟਿੰਗਜ਼',
    logout: 'ਲਾਗ ਆਊਟ',
    language: 'ਭਾਸ਼ਾ',
    darkMode: 'ਡਾਰਕ ਮੋਡ',
    
    // Dashboard
    welcomeMessage: 'ਕ੃ਸੀ ਸਮਾਰਟ ਵਿੱਚ ਸਵਾਗਤ ਹੈ',
    let: 'ਆਓ',
    grow: 'ਸਮਾਰਟ ਤਰੀਕੇ ਨਾਲ ਵਧੋ',
    earn: 'ਹੋਰ ਕਮਾਓ',
    welcome: 'ਸਵਾਗਤ ਹੈ',
    farmSize: 'ਫਾਰਮ ਦਾ ਆਕਾਰ',
    totalExpenses: 'ਕੁੱਲ ਖਰਚ',
    totalRevenue: 'ਕੁੱਲ ਰਾਜਸਵ',
    activeCrops: 'ਸਕਿਰਿਆ ਫਸਲਾਂ',
    activeAlerts: 'ਸਕਿਰਿਆ ਸਾਵਧਾਨੀਆਂ',
    quickActions: 'ਤੇਜ਼ ਕਰਮ',
    getCropRecommendation: 'ਫਸਲ ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ',
    checkWeather: 'ਮੌਸਮ ਦੀ ਜਾਂਚ ਕਰੋ',
    detectDisease: 'ਬਿਮਾਰੀ ਦਾ ਪਤਾ ਲਗਾਓ',
    trackExpenses: 'ਖਰਚ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ',
    viewSchemes: 'ਯੋਜਨਾਵਾਂ ਦੇਖੋ',
    
    // Weather Monitoring
    weatherMonitoringSystem: 'ਮੌਸਮ ਨਿਗਰਾਨੀ ਸਿਸਟਮ',
    realtimeWeatherData: 'ਆਪਣੀ ਖੇਤੀ ਸਥਿਤੀ ਲਈ ਸਮਾਂ-ਮਾਤ ਮੌਸਮ ਡਾਟਾ ਅਤੇ ਪੂਰਵਾਵਲੋਕਨ',
    enterLocation: 'ਸਥਿਤੀ ਦਾਖਲ ਕਰੋ (ਜਿਵੇਂ, ਪੰਜਾਬ, ਹਰਿਆਣਾ)',
    getWeather: 'ਮੌਸਮ ਪ੍ਰਾਪਤ ਕਰੋ',
    fetching: 'ਅਣੂ ਰਹੇ ਹਨ...',
    currentWeather: 'ਮੌਜੂਦਾ ਮੌਸਮ',
    humidity: 'ਨਮੀ',
    precipitation: 'ਮੀਂਹ',
    windSpeed: 'ਹਵਾ ਦੀ ਗਤੀ',
    forecast: 'ਪੂਰਵਾਵਲੋਕਨ',
    failedToFetchWeather: 'ਮੌਸਮ ਡਾਟਾ ਪ੍ਰਾਪਤ ਕਰਨ ਵਿੱਚ ਵਿਫਲ',
    pleaseEnterLocation: 'ਕਿਰਪਾ ਕਰਕੇ ਸਥਿਤੀ ਦਰਜ ਕਰੋ',
    
    // Disease Detection
    diseaseDetectionSystem: 'ਬਿਮਾਰੀ ਪਛਾਣ ਪ੍ਰਣਾਲੀ',
    uploadCropImage: 'ਆਪਣੀ ਫਸਲ ਦੀ ਤਸਵੀਰ ਇੱਥੇ ਅਪਲੋਡ ਕਰੋ',
    clickToUpload: 'ਬ੍ਰਾਊਜ਼ ਕਰਨ ਲਈ ਕਲਿਕ ਕਰੋ ਜਾਂ ਖਿੱਚ ਕੇ ਛੱਡੋ',
    analyzeImage: 'ਤਸਵੀਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    selectImage: 'ਤਸਵੀਰ ਚੁਣੋ',
    diseaseDetected: 'ਬਿਮਾਰੀ ਮਿਲੀ',
    noDisease: 'ਕੋਈ ਬਿਮਾਰੀ ਨਹੀਂ ਮਿਲੀ',
    confidence: 'ਭਰੋਸਾ',
    severity: 'ਗੰਭੀਰਤਾ',
    treatment: 'ਇਲਾਜ',
    pleaseSelectImage: 'ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਤਸਵੀਰ ਚੁਣੋ',
    failedToAnalyzeImage: 'ਤਸਵੀਰ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਨ ਵਿੱਚ ਵਿਫਲ',
    
    // Crop Recommendation
    cropRecommendationForm: 'ਫਸਲ ਸਿਫਾਰਸ਼',
    soilType: 'ਮਿੱਟੀ ਦੀ ਕਿਸਮ',
    location: 'ਸਥਾਨ',
    season: '਋ਤੂ',
    temperature: 'ਤਾਪਮਾਨ (°C)',
    rainfall: 'ਮੀਂਹ (ਮਿਮੀ)',
    clay: 'ਚਿਕਨੀ ਮਿੱਟੀ',
    loam: 'ਲੋਮ',
    sandy: 'ਰੇਤਲੀ',
    peat: 'ਪੀਟ',
    kharif: 'ਖਰੀਫ (ਅਪ੍ਰੈਲ-ਅਕਤੂਬਰ)',
    rabi: 'ਰਬੀ (ਅਕਤੂਬਰ-ਮਾਰਚ)',
    summer: 'ਗਰਮੀ (ਮਾਰਚ-ਜੂਨ)',
    getRecommendation: 'ਸਿਫਾਰਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ',
    recommendedCrops: 'ਸਿਫਾਰਿਸ਼ ਕੀਤੀਆਂ ਫਸਲਾਂ',
    crop: 'ਫਸਲ',
    suitability: 'ਢੁਕਵੀਂਤਾ',
    benefits: 'ਫਾਇਦੇ',
    
    // Smart Irrigation
    smartIrrigationSystem: 'ਸਮਾਰਟ ਸਿੰਚਾਈ ਪ੍ਰਣਾਲੀ',
    cropType: 'ਫਸਲ ਦੀ ਕਿਸਮ',
    rice: 'ਚਾਵਲ',
    wheat: 'ਕਣਕ',
    corn: 'ਮਕਈ',
    cotton: 'ਕਪਾਸ',
    sugarcane: 'ਗੰਨਾ',
    potato: 'ਆਲੂ',
    getAdvice: 'ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ',
    irrigationSchedule: 'ਸਿੰਚਾਈ ਸਮਚੌੜ',
    frequency: 'ਅਕਸਰਤਾ',
    waterQuantity: 'ਪਾਣੀ ਦੀ ਮਾਤਰਾ',
    duration: 'ਅਵਧੀ',
    
    // Marketplace
    farmerMarketplace: 'ਕਿਸਾਨ ਬਾਜ਼ਾਰ',
    buyAndSell: 'ਕਿਸੇ ਵੀ ਵਿਚੌਲੇ ਤੋਂ ਬਿਨਾਂ ਸਿੱਧਾ ਖੇਤੀ ਉਤਪਾਦ ਖਰੀਦੋ ਅਤੇ ਵੇਚੋ',
    search: 'ਉਤਪਾਦ ਖੋਜੋ...',
    searchProducts: 'ਉਤਪਾਦ ਖੋਜੋ',
    cart: 'ਕਾਰਟ',
    addToCart: 'ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
    removeFromCart: 'ਕਾਰਟ ਤੋਂ ਹਟਾਓ',
    quantity: 'ਮਾਤਰਾ',
    price: 'ਕੀਮਤ',
    seller: 'ਵਿਕਰੇਤਾ',
    rating: 'ਰੇਟਿੰਗ',
    totalPrice: 'ਕੁੱਲ ਕੀਮਤ',
    checkout: 'ਚੈੱਕਆਉਟ',
    noItemsInCart: 'ਕਾਰਟ ਵਿੱਚ ਕੋਈ ਆਈਟਮ ਨਹੀਂ',
    
    // Government Schemes
    governmentSchemes: 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ',
    exploreAndApply: 'ਕਿਸਾਨਾਂ ਲਈ ਸਰਕਾਰੀ ਸਮਰਥਨ ਯੋਜਨਾਵਾਂ ਦੀ ਖੋਜ ਕਰੋ ਅਤੇ ਅਰਜ ਲਗਾਓ',
    availableSchemes: 'ਉਪਲਬਧ ਯੋਜਨਾਵਾਂ',
    schemeType: 'ਯੋਜਨਾ ਦੀ ਕਿਸਮ',
    eligibility: 'ਯੋਗਤਾ',
    benefits: 'ਫਾਇਦੇ',
    applyNow: 'ਹੁਣ ਅਰਜ ਦਿਓ',
    learnMore: 'ਹੋਰ ਜਾਣੋ',
    incomeSupport: 'ਆਮਦਨ ਸਮਰਥਨ',
    insurance: 'ਬੀਮਾ',
    advisoryScheme: 'ਸਲਾਹ',
    credit: 'ਕ੍ਰੈਡਿਟ',
    
    // Crop Advisory
    cropAdvisorySystem: 'ਫਸਲ ਸਲਾਹ ਪ੍ਰਣਾਲੀ',
    getPersonalizedAdvice: 'ਆਪਣੀ ਖੇਤੀ ਦੀ ਸਥਿਤੀ ਦੇ ਆਧਾਰ ਤੇ ਵਿਅਕਤੀਗਤ ਫਸਲ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ',
    advisoryTips: 'ਸਲਾਹ ਦੀਆਂ ਸੁਝਾਈਆਂ',
    soilManagement: 'ਮਿੱਟੀ ਦਾ ਪ੍ਰਬੰਧਨ',
    pestManagement: 'ਕੀਟ ਪ੍ਰਬੰਧਨ',
    weatherAdvice: 'ਮੌਸਮ ਦੀ ਸਲਾਹ',
    harvestingTips: 'ਫਸਲ ਕੱਟਣ ਦੀਆਂ ਸੁਝਾਈਆਂ',
    
    // Expense Tracker
    expenseTracker: 'ਖਰਚ ਟ੍ਰੈਕਰ',
    manageYourFarmExpenses: 'ਆਪਣੀ ਖੇਤੀ ਦੇ ਖਰਚਿਆਂ ਨੂੰ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਢੰਗ ਨਾਲ ਪ੍ਰਬੰਧਿਤ ਕਰੋ',
    addExpense: 'ਖਰਚ ਸ਼ਾਮਲ ਕਰੋ',
    category: 'ਸ਼੍ਰੇਣੀ',
    seeds: 'ਬੀਜ',
    fertilizer: 'ਖਾਦ',
    labor: 'ਮਜ਼ਦੂਰੀ',
    equipment: 'ਉਪਕਰਣ',
    pesticide: 'ਕੀਟਨਾਸ਼ਕ',
    waterIrrigation: 'ਪਾਣੀ/ਸਿੰਚਾਈ',
    transportation: 'ਆਵਾਜਾਈ',
    other: 'ਹੋਰ',
    date: 'ਤਾਰੀਖ',
    description: 'ਵਿਵਰਣ',
    amount: 'ਰਕਮ',
    addNew: 'ਨਿਆਂ ਸ਼ਾਮਲ ਕਰੋ',
    totalExpensesAmount: 'ਕੁੱਲ ਖਰਚ',
    expenseAnalysis: 'ਖਰਚ ਵਿਸ਼ਲੇਸ਼ਣ',
    monthlyBreakdown: 'ਮਹੀਨੇ ਵਾਰ ਵਿਭਾਜਨ',
    categoryBreakdown: 'ਸ਼੍ਰੇਣੀ ਵਿਭਾਜਨ',
    
    // Common
    submit: 'ਜਮਾ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    error: 'ਗ਼ਲਤੀ',
    success: 'ਸਧਾਰਨ',
    fillAllFields: 'ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਜ਼ਰੂਰੀ ਖੇਤ ਭਰੋ',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
